### ISSUE TITLE
Disable sending the message when the input field is empty

### ISSUE THREAD

**Issue by Suyash-Purwar** [gita/Bhagavad-Gita-AI#30]
![image](https://user-images.githubusercontent.com/33785844/218242347-beb209a9-d073-454b-ad89-4f424aa14ca0.png)

Fix:

Option 1: For an empty message, maybe it should send a message something like - "What worries you my child?" 

Option 2: Disable sending the empty message altogether by disabling the button and reducing its opacity by .5 maybe. The button will be enabled (and have full opacity) when the input field is not empty.

**Comment by Suyash-Purwar** [comment]
I'd like to work on this issue and resolve it by the coming week's end. So, can it be assigned to me?

**Comment by samanyougarg** [comment]
@Suyash-Purwar Sure, assigning. Please fix within the next few hours though.

**Comment by Suyash-Purwar** [comment]
Sure! Should I go with Option 2?

**Comment by samanyougarg** [comment]
Option 2 is better, yes.
